### ISSUE TITLE
Create a method to set logging level

### ISSUE THREAD

**Issue by EduardKaverinskyi** [CyberAlpaca/squish-api-python-extension#10]

**Comment by pawtom** [comment]
I would follow setLevel(level) from the Python logging library 
(https://docs.python.org/3/library/logging.html).

The level parameters should accept both an int value and a string implementation of log level.

So both use cases should be possible:
`
from squape import report
report.set_level(report.LogLevel.DEBUG)
report.set_level("DEBUG")
`
