### ISSUE TITLE
enable_loglevel_in_test_module() causes crash of the squishrunner

### ISSUE THREAD

**Issue by EduardKaverinskyi** [CyberAlpaca/squish-api-python-extension#19]
`    squape.report.enable_loglevel_in_test_module(),`
`    squape.report.LOGLEVEL = squape.report.LogLevel.DEBUG`
`    with logScreenshotOnPass(True):
            test.passes("I am pass", "Pass details")`

For the above test scenario, if we enable loglevel in test script, and then set the report level to DEBUG, then, while executing testSettings context manager, squishserver process will crash with the following message:

![obraz](https://user-images.githubusercontent.com/108861789/235181143-1ef5b800-5238-4765-8991-46af551de132.png)

If the loglevel is set to anything else except DEBUG, testcase will finish it's execution successfully.
The same will happen if at least one of the three steps (enable loglevel, set report to DEBUG, use testSettings context manager) will not be excecuted.

**Comment by Adakar** [comment]
@EduardKaverinskyi I can't reproduce it with the latest version, could you please retest it?

**Comment by EduardKaverinskyi** [comment]
I retested on the main branch, and it also works for me.

**Comment by EduardKaverinskyi** [comment]
While running unit tests, the issue occurred again:

![image](https://github.com/CyberAlpaca/squish-api-python-extension/assets/108861789/571de5a4-cf72-4999-909b-88f495c77a17)

**Comment by Adakar** [comment]
Can't reproduce with 0.2.0 version,
