### ISSUE TITLE
Lack of support for both squishrunner execution and squishtest module usage

### ISSUE THREAD

**Issue by EduardKaverinskyi** [CyberAlpaca/squish-api-python-extension#26]
We should implement our library in such a way, that it is possible to use it out of the both from squishrunner (for example from Squish IDE), and outside of the squishrunner, using the squishtest python module.

**Comment by pawtom** [comment]
One way to check if squishrunner is used or squishtest module could be to check if environment variables SQUISHRUNNER_PORT and SQUISHRUNNER_HOST are set.
