### ISSUE TITLE
Inconsistant function description for _is_level_enabled in report module

### ISSUE THREAD

**Issue by EduardKaverinskyi** [CyberAlpaca/squish-api-python-extension#31]
The function description is following:

>   Returns:
>           bool: True if level is higher then LOGLEVEL, False otherwise

But the function implementation is:
   return LOGLEVEL <= level

If the values are equal, it will also return True, while level would not be higher than LOGLEVEL.

If this description is correct, the function should be:
return level > LOGLEVEL

Otherwise, it should be changed

**Comment by Adakar** [comment]
Thanks. Could you please fix the docstring?
