### ISSUE TITLE
Video module does not replace the video recording properly in the report generated by reportgen

### ISSUE THREAD

**Issue by EduardKaverinskyi** [CyberAlpaca/squish-api-python-extension#35]
If the reportgen used, the attached video recording would show the proper content, but will have it's size unmodified, so if the original video was 15 MB, the replaced video would also be 15 MB in size, but it will be 1 second placeholder, as in resources.

**Comment by Adakar** [comment]
It seems to be a Squish bug. It should be documented.

**Comment by EduardKaverinskyi** [comment]
Connected issue: https://gitea.froglogic.com/Products/squish/pulls/672#issuecomment-15891
